--liquibase formatted sql

--This is for the sparrow_dss schema

--logicalFilePath: createPredefinedSession17.sql

--changeset cschroed:createPredefinedSessionSequence
CREATE SEQUENCE  "PREDEFINED_SESSION_SEQ"  MINVALUE 1 MAXVALUE 99999999999999999999999999 INCREMENT BY 1 START WITH 2424 CACHE 20 ORDER  NOCYCLE  NOPARTITION ;
--rollback drop sequence "PREDEFINED_SESSION_SEQ";

--changeset cschroed:createPredefinedSession
CREATE TABLE "PREDEFINED_SESSION" 
(	"PREDEFINED_SESSION_ID" NUMBER(9,0), 
	"UNIQUE_CODE" VARCHAR2(60), 
	"SPARROW_MODEL_ID" NUMBER(9,0), 
	"PREDEFINED_TYPE" VARCHAR2(10), 
	"APPROVED" CHAR(1), 
	"NAME" VARCHAR2(60), 
	"DESCRIPTION" NCLOB, 
	"SORT_ORDER" NUMBER(2,0) DEFAULT (0), 
	"CONTEXT_STRING" NCLOB, 
	"ADD_DATE" DATE, 
	"ADD_BY" VARCHAR2(60), 
	"ADD_NOTE" NCLOB, 
	"ADD_CONTACT_INFO" NCLOB, 
	"GROUP_NAME" VARCHAR2(60)
) ;

COMMENT ON COLUMN "PREDEFINED_SESSION"."PREDEFINED_SESSION_ID" IS 'Database unique ID';
COMMENT ON COLUMN "PREDEFINED_SESSION"."UNIQUE_CODE" IS 'User speced unique code.  Allows a more memorable id than the PK';
COMMENT ON COLUMN "PREDEFINED_SESSION"."SPARROW_MODEL_ID" IS 'The model this pre-theme is for.  CONSTAINED';
COMMENT ON COLUMN "PREDEFINED_SESSION"."PREDEFINED_TYPE" IS 'CONSTRAINED TO: FEATURED, LISTED or UNLISTED';
COMMENT ON COLUMN "PREDEFINED_SESSION"."APPROVED" IS 'CONSTRAINED TO: T or F';
COMMENT ON COLUMN "PREDEFINED_SESSION"."NAME" IS 'A display name';
COMMENT ON COLUMN "PREDEFINED_SESSION"."DESCRIPTION" IS 'A description, possibly w/ some html.';
COMMENT ON COLUMN "PREDEFINED_SESSION"."SORT_ORDER" IS 'A low to high sorting value within a model.';
COMMENT ON COLUMN "PREDEFINED_SESSION"."CONTEXT_STRING" IS 'The actual text of the predefined theme.';
COMMENT ON COLUMN "PREDEFINED_SESSION"."ADD_DATE" IS 'The date-time the theme was added.';
COMMENT ON COLUMN "PREDEFINED_SESSION"."ADD_BY" IS 'The person who added the pre-theme.';
COMMENT ON COLUMN "PREDEFINED_SESSION"."ADD_NOTE" IS 'A note by the creator to the approving admin.';
COMMENT ON COLUMN "PREDEFINED_SESSION"."ADD_CONTACT_INFO" IS 'Contact info for the person creating the theme.';
COMMENT ON COLUMN "PREDEFINED_SESSION"."GROUP_NAME" IS 'User speced category to allow grouping within a model';

--rollback drop table PREDEFINED_SESSION;

--changeset cschroed:createPredefinedSessionPkIndex

CREATE UNIQUE INDEX "PREDEFINED_SESSION_PK" ON "PREDEFINED_SESSION" ("PREDEFINED_SESSION_ID");

--rollback drop index "PREDEFINED_SESSION_PK";

--changeset cschroed:createPredefinedSessionUniqueCodeIndex
CREATE UNIQUE INDEX "PREDEFINED_SESSION_UNIQUE_CODE" ON "PREDEFINED_SESSION" ("UNIQUE_CODE");
--rollback drop index "PREDEFINED_SESSION_UNIQUE_CODE";

--changeset cschroed:addConstraintPREDEFINED_SESSION_UNIQUE_CODEToPredefinedSession
ALTER TABLE "PREDEFINED_SESSION" ADD CONSTRAINT "PREDEFINED_SESSION_UNIQUE_CODE" UNIQUE ("UNIQUE_CODE")
USING INDEX  ENABLE;
--rollback ALTER TABLE "PREDEFINED_SESSION" DROP CONSTRAINT "PREDEFINED_SESSION_UNIQUE_CODE";

--changeset cschroed:addConstraintPREDEFINED_SESSION_PKToPredefinedSession
ALTER TABLE "PREDEFINED_SESSION" ADD CONSTRAINT "PREDEFINED_SESSION_PK" PRIMARY KEY ("PREDEFINED_SESSION_ID")
USING INDEX  ENABLE;
--rollback ALTER TABLE "PREDEFINED_SESSION" DROP CONSTRAINT "PREDEFINED_SESSION_PK";

--changeset cschroed:addConstraintPREDEFINED_CONTEXT_TYPEToPredefinedSession
ALTER TABLE "PREDEFINED_SESSION" ADD CONSTRAINT "PREDEFINED_CONTEXT_TYPE" CHECK (PREDEFINED_TYPE IN ('FEATURED', 'LISTED', 'UNLISTED')) ENABLE;
--rollback ALTER TABLE "PREDEFINED_SESSION" DROP CONSTRAINT "PREDEFINED_CONTEXT_TYPE";

--changeset cschroed:addConstraintPREDEFINED_CONTEXT_APPROVEDToPredefinedSession
ALTER TABLE "PREDEFINED_SESSION" ADD CONSTRAINT "PREDEFINED_CONTEXT_APPROVED" CHECK (APPROVED IN ('T', 'F')) ENABLE;
--rollback ALTER TABLE "PREDEFINED_SESSION" DROP CONSTRAINT "PREDEFINED_CONTEXT_APPROVED";

--changeset cschroed:enablePredefiniedSessionNotNullConstraintOnCONTEXT_STRING
ALTER TABLE "PREDEFINED_SESSION" MODIFY ("CONTEXT_STRING" NOT NULL ENABLE);
--rollback   ALTER TABLE "PREDEFINED_SESSION" MODIFY ("CONTEXT_STRING" NOT NULL DISABLE);

--changeset cschroed:enablePredefiniedSessionNotNullConstraintOnNAME
ALTER TABLE "PREDEFINED_SESSION" MODIFY ("NAME" NOT NULL ENABLE);
--rollback   ALTER TABLE "PREDEFINED_SESSION" MODIFY ("NAME" NOT NULL DISABLE);

--changeset cschroed:enablePredefiniedSessionNotNullConstraintOnAPPROVED
ALTER TABLE "PREDEFINED_SESSION" MODIFY ("APPROVED" NOT NULL ENABLE);
--rollback   ALTER TABLE "PREDEFINED_SESSION" MODIFY ("APPROVED" NOT NULL DISABLE);

--changeset cschroed:enablePredefiniedSessionNotNullConstraintOnPREDEFINED_TYPE
ALTER TABLE "PREDEFINED_SESSION" MODIFY ("PREDEFINED_TYPE" NOT NULL ENABLE);
--rollback   ALTER TABLE "PREDEFINED_SESSION" MODIFY ("PREDEFINED_TYPE" NOT NULL DISABLE);

--changeset cschroed:enablePredefiniedSessionNotNullConstraintOnSPARROW_MODEL_ID
ALTER TABLE "PREDEFINED_SESSION" MODIFY ("SPARROW_MODEL_ID" NOT NULL ENABLE);
--rollback   ALTER TABLE "PREDEFINED_SESSION" MODIFY ("SPARROW_MODEL_ID" NOT NULL DISABLE);

--changeset cschroed:enablePredefiniedSessionNotNullConstraintOnUNIQUE_CODE
ALTER TABLE "PREDEFINED_SESSION" MODIFY ("UNIQUE_CODE" NOT NULL ENABLE);
--rollback   ALTER TABLE "PREDEFINED_SESSION" MODIFY ("UNIQUE_CODE" NOT NULL DISABLE);


--changeset cschroed:enableNotNullConstraintOnPREDEFINED_SESSION_ID
ALTER TABLE "PREDEFINED_SESSION" MODIFY ("PREDEFINED_SESSION_ID" NOT NULL ENABLE);
--rollback ALTER TABLE "PREDEFINED_SESSION" MODIFY ("PREDEFINED_SESSION_ID" NOT NULL DISABLE);


--changeset cschroed:addSparrowModelIdFKConstraintToPredefinedSession
ALTER TABLE "PREDEFINED_SESSION" ADD CONSTRAINT "PREDEFINED_SESSION_SP_MODEL_FK" FOREIGN KEY ("SPARROW_MODEL_ID")
REFERENCES "SPARROW_MODEL" ("SPARROW_MODEL_ID") ON DELETE CASCADE DISABLE;
--rollback ALTER TABLE "PREDEFINED_SESSION" DROP CONSTRAINT "PREDEFINED_SESSION_SP_MODEL_FK";